spring:
  application:
    name: movieflix-backend

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/movieflix}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    default-property-inclusion: non_null

server:
  port: ${PORT:8080}
  error:
    include-message: always
    include-binding-errors: always

# Application Properties
app:
  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: 86400000  # 24 hours
    refresh-expiration-ms: 604800000  # 7 days

  omdb:
    api-key: ${OMDB_API_KEY}
    base-url: http://www.omdbapi.com/

  cache:
    expiry-hours: 24

logging:
  level:
    com.moengage: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN

