spring:
  application:
    name: movieflix-backend

  datasource:
    url: jdbc:h2:mem:movieflix
    driver-class-name: org.h2.Driver
    username: sa
    password: 
    
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

  jackson:
    default-property-inclusion: non_null

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

# Application Properties
app:
  jwt:
    secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
    expiration-ms: 86400000  # 24 hours
    refresh-expiration-ms: 604800000  # 7 days

  omdb:
    api-key: ${OMDB_API_KEY:f1223943}
    base-url: http://www.omdbapi.com/

  cache:
    expiry-hours: 24

logging:
  level:
    com.moengage: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG

# SpringDoc OpenAPI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    default-models-expand-depth: 1
    default-model-expand-depth: 1

